z_query_smr01_ltt <- paste("select LINK_NO, ADMISSION_DATE, DISCHARGE_DATE,",
                           "CIS_MARKER, POSTCODE, SPECIALTY, DISCHARGE_TYPE,",
                           "HBTREAT_CURRENTDATE, SEX,",
                           "CASE WHEN ADMISSION_TYPE BETWEEN 20 AND 48 OR",
                           "ADMISSION_TYPE = 18",
                           "THEN '2'",
                           "WHEN ADMISSION_TYPE BETWEEN 10 AND 12 OR",
                           "ADMISSION_TYPE = 19",
                           "THEN '1'",
                           "ELSE 'NULL'",
                           "END admgrp,",
                           "CASE WHEN ADMISSION_TRANSFER_FROM IN",
                           "('20','21','22','23','24','25','26','27','28',",
                           "'29')",
                           "THEN '1'",
                           "WHEN ADMISSION_TRANSFER_FROM IN",
                           "('60','61','62','63','64','65','66','67','68',",
                           "'69', '70')",
                           "THEN '2'",
                           "WHEN ADMISSION_TRANSFER_FROM IN",
                           "('10','11','12','13','14','15','16','17','18',",
                           "'19')",
                           "THEN '3'",
                           "WHEN ADMISSION_TRANSFER_FROM IN",
                           "('30','31','32','33','34','35','36','37','38',",
                           "'39')",
                           "THEN '4'",
                           "WHEN ADMISSION_TRANSFER_FROM IN",
                           "('50','51','52','53','54','55','56','57','58',",
                           "'59','5A','5B','5C', '5D', '5E', '5F', '5G')",
                           "THEN '5'",
                           "WHEN ADMISSION_TRANSFER_FROM IN",
                           "('40','41','42','43','44','45','46','47','48',",
                           "'49','4A','4B','4C', '4D', '4E', '4F', '4G')",
                           "THEN '6'",
                           "ELSE 'NULL'",
                           "END admfgrp,",
                           "CASE WHEN SPECIALTY IN",
                           "('C1','C11','C12','C13','C4','C41','C42','C5',",
                           "'C6','C7','C8','C9','CA','CB','D3','D4','D5',",
                           "'D6','D8','F2')",
                           "THEN '2'",
                           "ELSE '1'",
                           "END surgmed,",
                           "CASE WHEN INPATIENT_DAYCASE_IDENTIFIER = 'I'",
                           "THEN '1'",
                           "WHEN INPATIENT_DAYCASE_IDENTIFIER = 'D'",
                           "THEN '2'",
                           "ELSE 'NULL'",
                           "END ipdc,",
                           "CASE WHEN age_in_years BETWEEN 0 AND 19 THEN '1'",
                           "WHEN age_in_years BETWEEN 20 AND 39 THEN '2'",
                           "WHEN age_in_years BETWEEN 40 AND 59 THEN '3'",
                           "WHEN age_in_years BETWEEN 60 AND 79 THEN '4'",
                           "WHEN age_in_years >= 80 THEN '5'",
                           "ELSE 'NULL'",
                           "END age_grp,",
                           "to_char(admission_date,'Q') AS quarter,",
                           "extract(year from admission_date) AS year",
                           "from SMR01_PI",
                           "where ADMISSION_DATE BETWEEN",
                           "{d", shQuote(z_start_date_trends),"} AND",
                           "{d", shQuote(z_end_date),"}",
                           "ORDER BY LINK_NO, ADMISSION_DATE, RECORD_TYPE,",
                           "DISCHARGE_DATE, ADMISSION, DISCHARGE, URI")

z_query_gro <- paste("select LINK_NO, DATE_OF_DEATH, HBRES_CURRENTDATE,",
                     "to_char(DATE_OF_DEATH,'Q') AS quarter,",
                     "extract(year from DATE_OF_DEATH) AS year",
                     "from ANALYSIS.GRO_DEATHS_C",
                     "where DATE_OF_DEATH >= {d", shQuote(z_start_date_trends),"}",
                     "ORDER BY LINK_NO")
